---
title: "Fibroblast timecourse normalising data"
output: 
---


```{r}
rm(list=ls())

# Load useful packages
if (!require("tidyverse")) {
  install.packages("tidyverse", dependencies = TRUE)
  library(tidyverse)
}

if (!require("BiocManager")) {
  install.packages("BiocManager", dependencies = TRUE)
}

if (!require("edgeR")) {
  BiocManager::install("edgeR")
  library(edgeR)
} 

if (!require("psych")) {
  install.packages("psych", dependencies = TRUE)
  library(psych)
} 
# Make a list of all the .txt files in your working directory just so you can see what's going on
X = list.files(".",".txt")

```


```{r}
# read the raw data file, and ensure "NaN" is interpreted as NA
data_start <- read.delim("CRM4952_TMT16_Dig_phos_m10.txt", na = c("NaN"), stringsAsFactors = F)
data_start <- data_start[-1,] # Remove the first row which is just junk
data_start[, 1:16] <- sapply(data_start[,1:16], as.numeric) # Make the data numeric
# Remove rows which contain NaN within the data columns
data_start <- data_start[rowSums(is.na(data_start[, 1:16])) == 0,]
```

```{r}
# Clean up majority protein IDs and select reviewed uniprot based on reviewed uniprot list 
uniprot<- read.delim("uniprot-proteome_UP000000589+reviewed_yes.tab", na = c("NaN"), stringsAsFactors = F)

#split all majority protein id's into different rows, keep only reviewed uniprot 

data <- data_start %>%
  mutate(Protein = as.list(strsplit(Proteins, ";"))) %>%
  unnest(Protein)

names(data_start)
names(data)

#identifying reviewed and not reviewed uniprots 
Reviewed_uniprot<- data[data$Protein %in% uniprot$Entry ,]
Not_reviewed_uniprot<- data[!data$Unique.identifier %in% Reviewed_uniprot$Unique.identifier ,]

Reviewed_uniprot<- Reviewed_uniprot %>%
  distinct(Unique.identifier, .keep_all= TRUE)

Not_reviewed_uniprot<- Not_reviewed_uniprot %>%
  distinct(Unique.identifier, .keep_all = TRUE)

data_uniprot<- rbind(Reviewed_uniprot, Not_reviewed_uniprot)
data_uniprot<- data_uniprot %>%
  dplyr::rename(uniprot = Protein) 


```


```{r}
# Create column containing protein_phosphosite_multiplicity

data_uniprot$Phosphosite <- paste0(data_uniprot$uniprot, "_", data_uniprot$Amino.acid, data_uniprot$Position, data_uniprot$Multiplicity)

```

```{r}
#Now split gene names and keep first gene name 

genes <- vector("list", length(data_uniprot$Gene.names)) # Create empty vector
for (i in 1:length(data_uniprot$Gene.names)) {
  genes[i] <- strsplit(data_uniprot$Gene.names[i], ";")
}
gene_names <- unlist(lapply(genes, '[', 1))
data_uniprot$main_gene <- gene_names

data_raw<- data_uniprot[,1:16]
```

```{r}
#See what raw data looks like 

boxplot(log2(data_raw), 
        main = "Raw data",
        xlab = 'TMT Sample', ylab = 'log2 of Intensity', notch = TRUE)


# can also look at density plots (like a distribution histogram)
plotDensities(log2(data_raw), 6, 
              main = 'Raw data')

# check the column totals (per channel sums)
format(round(colSums(data_raw), digits = 0), big.mark = ",")

# see how things cluster
plotMDS(log2(data_raw), 
        main = "SL/TMM clusters group by TMT experiment")
```

```{r}
#Sample loading normalisation

target <- mean(colSums(data_raw))
norm_facs<- target/colSums(data_raw)
data_sl<- sweep(data_raw, 2, norm_facs, FUN = "*")

# see what the SL normalised data look like
boxplot(log2(data_sl), 
        main = "Sample loading (SL)",
        xlab = 'TMT Sample', ylab = 'log2 of Intensity', notch = TRUE)

# can also look at density plots (like a distribution histogram)    
plotDensities(log2(data_sl), main = "SL data")

# check the columnn totals
format(round(colSums(data_sl), digits = 0), big.mark = ",")
```



```{r}
# Combine uniprot ID, protein names, gene names, normalised data

master_list <- cbind(data_uniprot$Phosphosite, data_uniprot$uniprot, data_uniprot$main_gene, data_uniprot$Protein.names, data_uniprot$Sequence.window, data_uniprot$Amino.acid, data_uniprot$Position,  data_sl)


colnames(master_list)[1:7]<- c("Phosphosite", "uniprot", "main_gene", "protein_name", "Sequence.window", "AA", "Position")

write.csv(master_list, "Fibroblast_phospho_normalised.csv", row.names = F)
```
