---
title: "BioDare2"
output: 
---
```{r}
#######################################################################################################################################
# Here we take the normalised data from Notebook 1 and use the BioDare2 website to calculate rhythmicity, phase and amplitude https://biodare2.ed.ac.uk/
# We have to format the data correctly for the BioDare2 website:
    # The easiest way to do it is in Excel. 
    # Open the .csv file, remove everything apart from the 1st column with identifier (e.g. Phosphosite), and the columns containing the intensity data. Then change the column names to only the timepoint (e.g. 3, 3, 3, 3, 9, etc). Then change those column headers to Number. 
    # Start a new experiment in BioDare and upload the data
    # For rhythmicity analysis, there is no concatenation of data. In the "Rhythmicity" tab, I used the default parameters: 
        #Data window- ignore, i.e. keep as 0 to 0
        #Input data: no dtr
        #Test method: BD2 eJTK
        #Analysis presets: eJTK Classic
    # For phase analysis, I concatenated the data to make it 2 days with duplicate data. The data was then log2 transformed. For amplitude calculation, data was concantenated but not log2 transformed. For both period and amplitude analysis, in the "Period analysis" tab, I used these parameters:
        #Data window- ignore, i.e. keep as 0 to 0
        #Input data: amp&baseline dtr
        #Expected periods: 23.5-24.5
        #Analysis method: MFourFit

#Then download the data from each analysis and join it to the normalised data file. 
# Input and output files for BioDare are saved in the subfolder "biodare_files"
# INPUTS = analysis .csv files from BioDare2, normalised data .csv files from Notebook 1
# OUTPUTS = normalised data for further analysis (.csv)
#
#######################################################################################################################################
```

```{r}
#setup

# Clear your workspace
rm(list=ls())

# Load useful packages
if (!require("tidyverse")) {
  install.packages("tidyverse", dependencies = TRUE)
  library(tidyverse)
}
```

```{r}
#load the analysis files from BioDare2

Vehicle_rhythmicity<- read.csv("./biodare_files/26213_job752d8b44.rhythmicity.csv", skip=20, stringsAsFactors = F) %>%
  dplyr::rename(Phosphosite = Data.Label) %>% #have to skip the first 20 rows as they are not useful
  select(Phosphosite, JTK.p.BH.Corrected)

Vehicle_phase<- read.csv("./biodare_files/26213_job4ad413e2-0006-405c-a682-e495f1ce8b9b.ppa.csv", skip = 11, stringsAsFactors = F) %>%
  dplyr::rename(Phosphosite = Group.Label) %>%
  select(Phosphosite, Circ..Phase.To.Zero)

Vehicle_amp<- read.csv("./biodare_files/26213_jobeeab4d99-005b-4e3c-857c-d722097e6017.ppa.csv", skip = 11, stringsAsFactors = F)%>%
  dplyr::rename(Phosphosite = Group.Label) %>%
  select(Phosphosite, Amplitude)

INK_rhythmicity<- read.csv("./biodare_files/26213_job7ce07726.rhythmicity.csv", skip=20, stringsAsFactors = F) %>%
  dplyr::rename(Phosphosite = Data.Label) %>%
  select(Phosphosite, JTK.p.BH.Corrected)

INK_phase<- read.csv("./biodare_files/26213_job2c1f6f79-f36c-4c65-b069-fbfddff179b0.ppa.csv", skip = 11, stringsAsFactors = F)%>%
  dplyr::rename(Phosphosite = Group.Label)%>%
  select(Phosphosite, Circ..Phase.To.Zero)

INK_amp<- read.csv("./biodare_files/26213_jobee076690-ed7d-4075-8c16-68e21d46c00b.ppa.csv", skip = 11, stringsAsFactors = F)%>%
  dplyr::rename(Phosphosite = Group.Label)%>%
  select(Phosphosite, Amplitude)


#load the normalised .csv files from Notebook 1
Vehicle_raw<- read.csv("All_phospho_Vehicle_normalised_data_brain_urea_notnormtoprot.csv", stringsAsFactors = F)
INK_raw<- read.csv("All_phospho_INK_normalised_data_brain_urea_notnormtoprot.csv", stringsAsFactors = F)
```


```{r}
#join normalised data to BioDare outputs 

Vehicle<- left_join(Vehicle_raw, Vehicle_rhythmicity, by = "Phosphosite")%>%
  dplyr::select(where(~!all(is.na(.x)))) %>%
  left_join(Vehicle_phase, by = "Phosphosite")%>%
  left_join(Vehicle_amp, by = "Phosphosite") %>%
  rename(pval = JTK.p.BH.Corrected,
         Phase = Circ..Phase.To.Zero)

Vehicle_rhythmic<- Vehicle %>%
  filter(pval <= 0.05) #2706

Vehicle_notrhythmic<- Vehicle %>%
  filter(pval >= 0.05) #4997

nrow(Vehicle_rhythmic)/ nrow(Vehicle) *100 #35%

#export data
write.csv(Vehicle_rhythmic, "Vehicle_phospho_brain_urea_not_to_proteome_Biodare2_eJTK_rhythmic.csv", row.names = F)
write.csv(Vehicle_notrhythmic, "Vehicle_phospho_brain_urea_not_to_proteome_Biodare2_eJTK_notrhythmic.csv", row.names = F)
write.csv(Vehicle, "Vehicle_phospho_brain_urea_not_to_proteome_Biodare2_eJTK_all.csv", row.names = F)
```

```{r}
#join normalised data to BioDare outputs 
INK<- left_join(INK_raw, INK_rhythmicity, by = "Phosphosite")%>%
  dplyr::select(where(~!all(is.na(.x)))) %>%
  left_join(INK_phase, by = "Phosphosite")%>%
  left_join(INK_amp, by = "Phosphosite") %>%
  rename(pval = JTK.p.BH.Corrected,
         Phase = Circ..Phase.To.Zero)

INK_rhythmic<- INK %>%
  filter(pval <= 0.05) #147

INK_notrhythmic<- INK %>%
  filter(pval >0.05) #7556

nrow(INK_rhythmic)/ nrow(INK) *100 #2%

#export data
write.csv(INK_rhythmic, "INK_phospho_brain_urea_not_to_proteome_Biodare2_eJTK_rhythmic.csv", row.names = F)
write.csv(INK_notrhythmic, "INK_phospho_brain_urea_not_to_proteome_Biodare2_eJTK_notrhythmic.csv", row.names = F)
write.csv(INK, "INK_phospho_brain_urea_not_to_proteome_Biodare2_eJTK_all.csv", row.names = F)
```

